### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by parthmalpathak** [tungdop2/ByteTrack_yolov5#6]
Hello, thanks for your work. Is there any clearer way of implementing this? I don't see a README.md. 

Thanks!

**Comment by tungdop2** [comment]
@parthmalpathak sorry i will update it later. You can go to yolov5/demo_track.py and see some arguments here.

**Comment by parthmalpathak** [comment]
Thanks for your reply! Just to confirm, is that the only file where changes have been made? Because there should be changes made ion order to train as well right considering we are passing yolov5 as an argument instead of yolox in --pretrained now.

**Comment by tungdop2** [comment]
Not only, there are some util files from ByteTrack.

**Comment by parthmalpathak** [comment]
Alright, I will have a look. Meanwhile, eagerly waiting for your README.md for implementation. Thanks!

**Comment by tungdop2** [comment]
@parthmalpathak i updated README, you can check and report again.
